[package]
name = "excel-to-csv"
version = "0.1.0"
authors = ["Sigurd Andreas Holsen <Sigurd.Andreas.Holsen@km.kongsberg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.16.1"
clap = "*"