[package]
name = "excel-to-txt"
version = "0.1.1"
authors = ["Sigurd Holsen <sighol@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.16.1"
clap = "2.33.0"